### ISSUE TITLE
Uncaught exception 'Zend\Session\Exception\RuntimeException' with message 'Session validation failed'

### ISSUE THREAD

**Issue by googlle** [zendframework/zf2#6390]
when installing the session validators 
```
'validators' => array(
'Zend\Session\Validator\RemoteAddr',
'Zend\Session\Validator\HttpUserAgent',
),
```
at the start of the session checks the validity of data (Httpuseragent or Remoteaddr)
https://github.com/zendframework/zf2/blob/master/library/Zend/Session/SessionManager.php#L110-L112
if the data is not valid displays errors
```
Fatal error: Uncaught exception 'Zend\Session\Exception\RuntimeException' with message 'Session validation failed' in C:\xampp\htdocs\application\vendor\zendframework\zendframework\library\Zend\Session\SessionManager.php:111 Stack trace: #0 C:\xampp\htdocs\application\module\Application\Module.php(81): Zend\Session\SessionManager->start() #1 C:\xampp\htdocs\application\module\Application\Module.php(29): Application\Module->bootstrapSession(Object(Zend\Mvc\MvcEvent)) #2 [internal function]: Application\Module->onBootstrap(Object(Zend\Mvc\MvcEvent)) #3 C:\xampp\htdocs\application\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #4 C:\xampp\htdocs\application\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('bootstrap', Object(Zend\Mvc\MvcEvent), Array) #5 C:\xampp\htdocs\application\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(156): Zen in C:\xampp\htdocs\application\vendor\zendframework\zendframework\library\Zend\Session\SessionManager.php on line 111
```

**Comment by samsonasik** [comment]
@googlle @Ocramius it can be closed as @Martin-P said above ;)

**Comment by Misikir** [comment]
@googlle @Ocramius @samsonasik @Martin-P  Is this issue [#6364](https://github.com/zendframework/zf2/issues/6364) fixed or I want to handle that exception. i look at the session manager documentation but it doesn't handle invalid session can someone give me an example?

**Comment by Martin-P** [comment]
@Misikir Issue #6364 was indeed fixed. It was a documentation issue and was fixed with https://github.com/zendframework/zf2-documentation/pull/1342

Regarding the exception, you can add a try/catch block and check for `Zend\Session\Exception\RuntimeException`:

```php
use Zend\Session\Exception\ExceptionInterface as SessionException;

try {
    // create session etc.
} catch (SessionException $exception) {
    echo 'Something went wrong with the session';
    // echo $exception;
}
```

**Comment by Misikir** [comment]
@Martin-P Thank you

**Comment by Martin-P** [comment]
@Misikir You're welcome

**Comment by googlle** [comment]
Thanks. Close this issue
