### ISSUE TITLE
Error language with zend 2

### ISSUE THREAD

**Issue by nvmanh** [zendframework/zf2#7173]
I'm a newbie of zend framework, and i have an issue with it. Who can help me find out my mistake?

I always get this error when code module login: i tried many solution, then i think the mistake here maybe relate language module. I used sample SanAythen (https://github.com/IgorDePaula/SanAuth)

```
Fatal error: Uncaught exception 'Zend\I18n\Exception\InvalidArgumentException' with message 'E:\xampp\htdocs\ZendSkeletonApplication\module\Application\config/../language/en_US.mo is not a valid gettext file' in E:\xampp\htdocs\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\I18n\Translator\Loader\Gettext.php:76 Stack trace: #0 E:\xampp\htdocs\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\I18n\Translator\Translator.php(660): Zend\I18n\Translator\Loader\Gettext->load('en_US', 'E:\\xampp\\htdocs...') #1 E:\xampp\htdocs\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\I18n\Translator\Translator.php(569): Zend\I18n\Translator\Translator->loadMessagesFromPatterns('default', 'en_US') #2 E:\xampp\htdocs\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\I18n\Translator\Translator.php(438): Zend\I18n\Translator\Translator->loadMessages('default', 'en_US') #3 E:\xampp\htdocs\ZendSkeletonApplication\vendor\zendframework\zendframework\libra in E:\xampp\htdocs\ZendSkeletonApplication\vendor\zendframework\zendframework\library\Zend\I18n\Translator\Loader\Gettext.php on line 76
```

Thank you very much!

**Comment by samsonasik** [comment]
not an issue. please ask in stackoverflow/mailing list for it. @nvmanh 

/cc @Ocramius it can be closed.
