### ISSUE TITLE
Class "Livraria\Entity\Categoria" is not a valid entity or mapped super class.

### ISSUE THREAD

**Issue by jhonnyscerni** [zendframework/zf2#7652]
```php
Stack trace:
#0 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\Driver\AnnotationDriver.php(91): Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass('Livraria\\Entity...')
#1 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain.php(102): Doctrine\ORM\Mapping\Driver\AnnotationDriver->loadMetadataForClass('Livraria\\Entity...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#2 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(151): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('Livraria\\Entity...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#4 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Livraria\\Entity...')
#5 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(216): Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata('Livraria\\Entity...')
#6 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php(281): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Livraria\\Entity...')
#7 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\orm\lib\Doctrine\ORM\Repository\DefaultRepositoryFactory.php(44): Doctrine\ORM\EntityManager->getClassMetadata('Livraria\\Entity...')
#8 C:\xampp\htdocs\projetos\cursozf2\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php(698): Doctrine\ORM\Repository\DefaultRepositoryFactory->getRepository(Object(Doctrine\ORM\EntityManager), 'Livraria\\Entity...')
#9 C:\xampp\htdocs\projetos\cursozf2\module\Livraria\src\Livraria\Controller\IndexController.php(15): Doctrine\ORM\EntityManager->getRepository('Livraria\\Entity...')
#10 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Livraria\Controller\IndexController->indexAction()
#11 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 C:\xampp\htdocs\projetos\cursozf2\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 C:\xampp\htdocs\projetos\cursozf2\public\index.php(21): Zend\Mvc\Application->run()
#21 {main}

```
![image](https://cloud.githubusercontent.com/assets/16142948/11791092/98ad1f76-a286-11e5-871d-7998f57c6786.png)

**Comment by sandrokeil** [comment]
@jhonnyscerni This is not a ZF2 issue. Please close it and check your Doctrine configuration. Maybe you have misspelled something.
